name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

      - name: Get PR diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          DIFF=$(git diff origin/${{ github.base_ref }}...HEAD)
          {
            echo "diff<<EOF"
            echo "$DIFF"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Get changed files
        id: files
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | head -20)
          {
            echo "files<<EOF"
            echo "$FILES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: AI Code Review
        id: review
        run: |
          PROJECT_CONTEXT=$(cat .github/about.md)

          read -r -d '' PROMPT <<'EOF'
You are an expert code reviewer for Elixpo-Chapter, a developer-first open source ecosystem of AI-powered tools and platforms.

PROJECT CONTEXT:
'"$PROJECT_CONTEXT"'

ELIXPO ECOSYSTEM OVERVIEW:
Elixpo is a collaborative ecosystem with 20+ open source projects including AI art generation (Elixpo Art), intelligent search (Elixpo Search), AI chatbots (Elixpo Chat), Discord bots (Jackey), and various other AI-powered tools. We focus on open, ethical, and accessible AI development with 100% open source licensing under GNU GPL-3.0.

Review this pull request and provide:
1. **Summary**: Brief overview of changes and their impact on the Elixpo ecosystem
2. **Code Quality**: Rate 1-10 considering open source best practices
3. **Potential Issues**: Security, bugs, performance, and compatibility concerns across projects
4. **Suggestions**: Improvements aligned with Elixpo's mission of accessible AI
5. **Testing**: What tests should be added/updated for the affected components
6. **Ecosystem Impact**: How changes affect other Elixpo projects or integrations

Changed files:
${{ steps.files.outputs.files }}

Diff (first 3000 chars):
$(echo '${{ steps.diff.outputs.diff }}' | head -c 3000)

Provide a concise, actionable review in markdown format.
EOF

          REVIEW=$(curl -s -X POST "https://text.pollinations.ai/openai" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.POLLI_PAT }}" \
            -d "{
              \"model\": \"gemini\",
              \"messages\": [{\"role\": \"user\", \"content\": $(echo "$PROMPT" | jq -Rs .)}],
              \"temperature\": 0.3,
              \"max_tokens\": 1500
            }" | jq -r '.choices[0].message.content')

          {
            echo "review<<EOF"
            echo "$REVIEW"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Post AI Review
        uses: actions/github-script@v6
        env:
          REVIEW_TEXT: ${{ steps.review.outputs.review }}
        with:
          script: |
            const reviewText = process.env.REVIEW_TEXT || "⚠️ No AI review text generated.";
            const review = `## 🤖 AI Code Review

${reviewText}

---

*This review was generated by AI. Please use human judgment for final decisions.*
`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            });
